[workspace]
members = [
    "crates/encore",
    "crates/minipak",
    "crates/stage1",
    "crates/stage2",
    "crates/pixie",
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
debug = true
codegen-units = 1
incremental = false
lto = "fat"
opt-level = "s"
