[workspace]
members = [
    "crates/encore",
    "crates/minipak",
    "crates/stage1",
    "crates/pixie",
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
debug = true
lto = "thin"
